### ISSUE TITLE
Error!

### ISSUE THREAD

**Issue by fvbatistoni** [devnoname120/google-play-book-downloader#20]
How do I generate aes_key.bin?
Where do I find manifest.json?
Where do I find segments.txt, segments.json?
I am trying to download aqqGEAAAQBAJ book as epub

**Comment by fvbatistoni** [comment]
Error! Download or decrypt failed (url: https://play.google.com/books/volumes/aqqGEAAAQBAJ/content/segment?start=bookwire_advertisement5&cds=2&authuser=2&source=gbs_content_api) failed with 'utf-8' codec can't decode byte 0xd0 in position 0: invalid continuation byte

**Comment by devnoname120** [comment]
First line of the instructions that you obviously didn't read.
