### ISSUE TITLE
Error when installing lxml

### ISSUE THREAD

**Issue by NlckN4me** [devnoname120/google-play-book-downloader#22]
`Installing dependencies from lock file

Package operations: 18 installs, 0 updates, 0 removals

  - Installing lxml (5.2.2): Failed

  ChefBuildError

  Backend subprocess exited when trying to invoke build_wheel

  <string>:67: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  Building lxml version 5.2.2.
  Building without Cython.
  Building against pre-built libxml2 andl libxslt libraries
  running bdist_wheel
  running build
  running build_py
  creating build\lib.win-amd64-cpython-313\lxml
  copying src\lxml\builder.py -> build\lib.win-amd64-cpython-313\lxml
  copying src\lxml\cssselect.py -> build\lib.win-amd64-cpython-313\lxml
  copying src\lxml\doctestcompare.py -> build\lib.win-amd64-cpython-313\lxml
  copying src\lxml\ElementInclude.py -> build\lib.win-amd64-cpython-313\lxml
  copying src\lxml\pyclasslookup.py -> build\lib.win-amd64-cpython-313\lxml
  copying src\lxml\sax.py -> build\lib.win-amd64-cpython-313\lxml
  copying src\lxml\usedoctest.py -> build\lib.win-amd64-cpython-313\lxml
  copying src\lxml\_elementpath.py -> build\lib.win-amd64-cpython-313\lxml
  copying src\lxml\__init__.py -> build\lib.win-amd64-cpython-313\lxml
  creating build\lib.win-amd64-cpython-313\lxml\includes
  copying src\lxml\includes\__init__.py -> build\lib.win-amd64-cpython-313\lxml\includes
  creating build\lib.win-amd64-cpython-313\lxml\html
  copying src\lxml\html\builder.py -> build\lib.win-amd64-cpython-313\lxml\html
  copying src\lxml\html\clean.py -> build\lib.win-amd64-cpython-313\lxml\html
  copying src\lxml\html\defs.py -> build\lib.win-amd64-cpython-313\lxml\html
  copying src\lxml\html\diff.py -> build\lib.win-amd64-cpython-313\lxml\html
  copying src\lxml\html\ElementSoup.py -> build\lib.win-amd64-cpython-313\lxml\html
  copying src\lxml\html\formfill.py -> build\lib.win-amd64-cpython-313\lxml\html
  copying src\lxml\html\html5parser.py -> build\lib.win-amd64-cpython-313\lxml\html
  copying src\lxml\html\soupparser.py -> build\lib.win-amd64-cpython-313\lxml\html
  copying src\lxml\html\usedoctest.py -> build\lib.win-amd64-cpython-313\lxml\html
  copying src\lxml\html\_diffcommand.py -> build\lib.win-amd64-cpython-313\lxml\html
  copying src\lxml\html\_html5builder.py -> build\lib.win-amd64-cpython-313\lxml\html
  copying src\lxml\html\_setmixin.py -> build\lib.win-amd64-cpython-313\lxml\html
  copying src\lxml\html\__init__.py -> build\lib.win-amd64-cpython-313\lxml\html
  creating build\lib.win-amd64-cpython-313\lxml\isoschematron
  copying src\lxml\isoschematron\__init__.py -> build\lib.win-amd64-cpython-313\lxml\isoschematron
  copying src\lxml\etree.h -> build\lib.win-amd64-cpython-313\lxml
  copying src\lxml\etree_api.h -> build\lib.win-amd64-cpython-313\lxml
  copying src\lxml\lxml.etree.h -> build\lib.win-amd64-cpython-313\lxml
  copying src\lxml\lxml.etree_api.h -> build\lib.win-amd64-cpython-313\lxml
  copying src\lxml\etree.pyx -> build\lib.win-amd64-cpython-313\lxml
  copying src\lxml\objectify.pyx -> build\lib.win-amd64-cpython-313\lxml
  copying src\lxml\apihelpers.pxi -> build\lib.win-amd64-cpython-313\lxml
  copying src\lxml\classlookup.pxi -> build\lib.win-amd64-cpython-313\lxml
  copying src\lxml\cleanup.pxi -> build\lib.win-amd64-cpython-313\lxml
  copying src\lxml\debug.pxi -> build\lib.win-amd64-cpython-313\lxml
  copying src\lxml\docloader.pxi -> build\lib.win-amd64-cpython-313\lxml
  copying src\lxml\dtd.pxi -> build\lib.win-amd64-cpython-313\lxml
  copying src\lxml\extensions.pxi -> build\lib.win-amd64-cpython-313\lxml
  copying src\lxml\iterparse.pxi -> build\lib.win-amd64-cpython-313\lxml
  copying src\lxml\nsclasses.pxi -> build\lib.win-amd64-cpython-313\lxml
  copying src\lxml\objectpath.pxi -> build\lib.win-amd64-cpython-313\lxml
  copying src\lxml\parser.pxi -> build\lib.win-amd64-cpython-313\lxml
  copying src\lxml\parsertarget.pxi -> build\lib.win-amd64-cpython-313\lxml
  copying src\lxml\proxy.pxi -> build\lib.win-amd64-cpython-313\lxml
  copying src\lxml\public-api.pxi -> build\lib.win-amd64-cpython-313\lxml
  copying src\lxml\readonlytree.pxi -> build\lib.win-amd64-cpython-313\lxml
  copying src\lxml\relaxng.pxi -> build\lib.win-amd64-cpython-313\lxml
  copying src\lxml\saxparser.pxi -> build\lib.win-amd64-cpython-313\lxml
  copying src\lxml\schematron.pxi -> build\lib.win-amd64-cpython-313\lxml
  copying src\lxml\serializer.pxi -> build\lib.win-amd64-cpython-313\lxml
  copying src\lxml\xinclude.pxi -> build\lib.win-amd64-cpython-313\lxml
  copying src\lxml\xmlerror.pxi -> build\lib.win-amd64-cpython-313\lxml
  copying src\lxml\xmlid.pxi -> build\lib.win-amd64-cpython-313\lxml
  copying src\lxml\xmlschema.pxi -> build\lib.win-amd64-cpython-313\lxml
  copying src\lxml\xpath.pxi -> build\lib.win-amd64-cpython-313\lxml
  copying src\lxml\xslt.pxi -> build\lib.win-amd64-cpython-313\lxml
  copying src\lxml\xsltext.pxi -> build\lib.win-amd64-cpython-313\lxml
  copying src\lxml\includes\c14n.pxd -> build\lib.win-amd64-cpython-313\lxml\includes
  copying src\lxml\includes\config.pxd -> build\lib.win-amd64-cpython-313\lxml\includes
  copying src\lxml\includes\dtdvalid.pxd -> build\lib.win-amd64-cpython-313\lxml\includes
  copying src\lxml\includes\etreepublic.pxd -> build\lib.win-amd64-cpython-313\lxml\includes
  copying src\lxml\includes\htmlparser.pxd -> build\lib.win-amd64-cpython-313\lxml\includes
  copying src\lxml\includes\relaxng.pxd -> build\lib.win-amd64-cpython-313\lxml\includes
  copying src\lxml\includes\schematron.pxd -> build\lib.win-amd64-cpython-313\lxml\includes
  copying src\lxml\includes\tree.pxd -> build\lib.win-amd64-cpython-313\lxml\includes
  copying src\lxml\includes\uri.pxd -> build\lib.win-amd64-cpython-313\lxml\includes
  copying src\lxml\includes\xinclude.pxd -> build\lib.win-amd64-cpython-313\lxml\includes
  copying src\lxml\includes\xmlerror.pxd -> build\lib.win-amd64-cpython-313\lxml\includes
  copying src\lxml\includes\xmlparser.pxd -> build\lib.win-amd64-cpython-313\lxml\includes
  copying src\lxml\includes\xmlschema.pxd -> build\lib.win-amd64-cpython-313\lxml\includes
  copying src\lxml\includes\xpath.pxd -> build\lib.win-amd64-cpython-313\lxml\includes
  copying src\lxml\includes\xslt.pxd -> build\lib.win-amd64-cpython-313\lxml\includes
  copying src\lxml\includes\__init__.pxd -> build\lib.win-amd64-cpython-313\lxml\includes
  copying src\lxml\includes\etree_defs.h -> build\lib.win-amd64-cpython-313\lxml\includes
  copying src\lxml\includes\lxml-version.h -> build\lib.win-amd64-cpython-313\lxml\includes
  creating build\lib.win-amd64-cpython-313\lxml\isoschematron\resources\rng
  copying src\lxml\isoschematron\resources\rng\iso-schematron.rng -> build\lib.win-amd64-cpython-313\lxml\isoschematron\resources\rng
  creating build\lib.win-amd64-cpython-313\lxml\isoschematron\resources\xsl
  copying src\lxml\isoschematron\resources\xsl\RNG2Schtrn.xsl -> build\lib.win-amd64-cpython-313\lxml\isoschematron\resources\xsl
  copying src\lxml\isoschematron\resources\xsl\XSD2Schtrn.xsl -> build\lib.win-amd64-cpython-313\lxml\isoschematron\resources\xsl
  creating build\lib.win-amd64-cpython-313\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
  copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_abstract_expand.xsl -> build\lib.win-amd64-cpython-313\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
  copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_dsdl_include.xsl -> build\lib.win-amd64-cpython-313\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
  copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_schematron_message.xsl -> build\lib.win-amd64-cpython-313\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
  copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_schematron_skeleton_for_xslt1.xsl -> build\lib.win-amd64-cpython-313\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
  copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_svrl_for_xslt1.xsl -> build\lib.win-amd64-cpython-313\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
  copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\readme.txt -> build\lib.win-amd64-cpython-313\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
  running build_ext
  building 'lxml.etree' extension
  creating build\temp.win-amd64-cpython-313\Release\src\lxml
  "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -DCYTHON_CLINE_IN_TRACEBACK=0 -Isrc -Isrc\lxml\includes -IC:\Users\User\AppData\Local\Temp\tmplk67smbv\.venv\include -IC:\Users\User\AppData\Local\Programs\Python\Python313\include -IC:\Users\User\AppData\Local\Programs\Python\Python313\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" /Tcsrc\lxml\etree.c /Fobuild\temp.win-amd64-cpython-313\Release\src\lxml\etree.obj -w
  cl : ¸í·ÉÁÙ warning D9025 : '/W3'À»(¸¦) '/w'(À¸)·Î ÀçÁ¤ÀÇÇÕ´Ï´Ù.
  etree.c
  C:\Users\User\AppData\Local\Temp\tmp617m9ds2\lxml-5.2.2\src\lxml\includes/etree_defs.h(12): fatal error C1083: Æ÷ÇÔ ÆÄÀÏÀ» ¿­ ¼ö ¾ø½À´Ï´Ù. 'libxml/xmlversion.h': No such file or directory
  Compile failed: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.41.34120\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
  "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -I/usr/include/libxml2 "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" /TcC:\Users\User\AppData\Local\Temp\xmlXPathInitupoie65q.c /Fo\Users\User\AppData\Local\Temp\xmlXPathInitupoie65q.obj
  xmlXPathInitupoie65q.c
  C:\Users\User\AppData\Local\Temp\xmlXPathInitupoie65q.c(1): fatal error C1083: Æ÷ÇÔ ÆÄÀÏÀ» ¿­ ¼ö ¾ø½À´Ï´Ù. 'libxml/xpath.h': No such file or directory
  *********************************************************************************
  Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
  *********************************************************************************
  error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.41.34120\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2

  at ~\AppData\Local\Programs\Python\Python313\Lib\site-packages\poetry\installation\chef.py:164 in _prepare
      160│
      161│                 error = ChefBuildError("\n\n".join(message_parts))
      162│
      163│             if error is not None:
    → 164│                 raise error from None
      165│
      166│             return path
      167│
      168│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with lxml (5.2.2) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "lxml (==5.2.2)"'.
`

The same error occurs when using this command
'pip wheel --no-cache-dir --use-pep517 "lxml (==5.2.2)"'

How to solve it?

**Comment by devnoname120** [comment]
Sorry I don't know look on the internet or ask on the lxml repo.

**Comment by NlckN4me** [comment]
I can install lxml 5.3.0. Can you modify the lxml to version 5.3.0 instead of 5.2.2?

**Comment by devnoname120** [comment]
Sure, please do a PR.

**Comment by NlckN4me** [comment]
Thank you for your help:)

**Comment by NlckN4me** [comment]
When I do "poetry run play-book-pdf-build books/hw4XEQAAQBAJ" 

Error occurs

[INFO] the manifest indicates that the book pages are ordered right to left. We will swap the order of the pages so that they show correctly in the PDF.
Merging 213 pages... (this can take a long time)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    import sys; from importlib import import_module; sys.argv = ['C:\\Users\\User\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\play-book-pdf-tool-tIPfZgGU-py3.13\\Scripts\\play-book-pdf-build.cmd', 'books/hw4XEQAAQBAJ']; sys.exit(import_module('play_book_pdf_tool.play_book_pdf_tool').pdf_generate())
                                                                                                                                                                                                                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\play-book-pdf-tool-tIPfZgGU-py3.13\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\play-book-pdf-tool-tIPfZgGU-py3.13\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\play-book-pdf-tool-tIPfZgGU-py3.13\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\play-book-pdf-tool-tIPfZgGU-py3.13\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\User\Documents\GitHub\google-play-book-downloader\play_book_pdf_tool\play_book_pdf_tool.py", line 63, in pdf_generate
    create_pdf(page_paths, tmp_pdf)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Documents\GitHub\google-play-book-downloader\play_book_pdf_tool\play_book_pdf_tool.py", line 89, in create_pdf
    img2pdf.convert(*image_paths, outputstream=output_pdf)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\play-book-pdf-tool-tIPfZgGU-py3.13\Lib\site-packages\img2pdf.py", line 2360, in convert
    ) in read_images(
         ~~~~~~~~~~~^
        rawdata,
        ^^^^^^^^
    ...<2 lines>...
        kwargs["rotation"],
        ^^^^^^^^^^^^^^^^^^^
    ):
    ^
  File "C:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\play-book-pdf-tool-tIPfZgGU-py3.13\Lib\site-packages\img2pdf.py", line 1682, in read_images
    pngidat, palette = parse_png(rawdata)
                       ~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\play-book-pdf-tool-tIPfZgGU-py3.13\Lib\site-packages\img2pdf.py", line 1526, in parse_png
    raise Exception("invalid png: %d %d %d" % (i, n, len(rawdata)))
Exception: invalid png: 7037 185273099 7040

How can I solve it?

P.S. I'm sorry to keep asking you questions.

**Comment by devnoname120** [comment]
@NlckN4me Open a new issue.
