### ISSUE TITLE
Error when run  zx google-play-book-downloader.mjs

### ISSUE THREAD

**Issue by kingjt9595** [devnoname120/google-play-book-downloader#5]
I tried a lot to solve this problem
I installed Java again
I reinstalled Python
And I did all the steps

But I still get the error

![image](https://github.com/devnoname120/google-play-book-downloader/assets/62213672/c14b85e8-f3bc-4bd1-8f45-fb4c007e9901)

**Comment by KodywithaK** [comment]
@kingjt9595 I was getting the same errors as you, until I tried this, so I believe it will work for you too:

I removed the  1st and 3rd arguments from the "copy as Node.js fetch", (i.e.)
```js
fetch({URL}, {
```
&
```js
,
  "body": null,
  "method": "GET"
});
```
leaving only

```js
15: const FETCH_OPTIONS = {
16:     "headers": {
            *your info here*
        }
39: };
```
then I removed the first $ from
```js
43: const book_dir = $`books/${BOOK_ID}`;
```
making it
```js
43: const book_dir = `books/${BOOK_ID}`;
```
and manually created the "google-play-downloader-main\books\\{BOOK_ID}".

After that, running the "zx google-play-book-downloader.mjs" worked perfectly!

**Comment by devnoname120** [comment]
I will make this part more user-friendly in a future version. Until then you will need to be careful when you copy/paste the object.
