### ISSUE TITLE
Pages of right-to-left mangas are not reordered (even/odd pages not swapped)

### ISSUE THREAD

**Issue by KodywithaK** [devnoname120/google-play-book-downloader#6]
## Summary
I don't know how many people will run into this same problem—as it may just be the eBooks I purchased are odd ducks, but if not—hopefully this helps

## Problem
I had an issue with my page order (the eBook was an official english translation of an eBook originally in japanese), so every odd numbered page starting from page 3 was on the opposite side of its intended 2-page spread

## Solution
With VSCode, I opened the "google-play-book-downloader\books\\***{BOOK_ID}***\pages.txt" file
- `Ctrl+H` "**(.*\n){2}**" in the ***Find*** field with RegEx enabled (to highlight all the odd numbered lines)
- `Alt+Enter` to Select All Occurrences of Find Match, minus the front & back covers
- `Right` to get the multiple cursors ready, then `Alt+Up` to move the odd numbered lines up 1 line
- Saved the file, then ran `poetry run play-book-pdf-build books/{BOOK_ID}` to output the eBook in its intended order

---
 
Thanks devnoname120, your program is a big help to backup all my books!

**Comment by devnoname120** [comment]
Thanks for your report.
Does the page ordering issue also happen if you open your ebook in Google Play Books? Or does this issue only happen in the PDF that is created with my tool?

**Comment by KodywithaK** [comment]
Just on the created pdfs, anytime the page order is right to left instead of left to right

**Comment by devnoname120** [comment]
@KodywithaK Interesting... Could you share the `manifest.json` file? You can censor the links inside that contain `&sig=` if you want.

**Comment by KodywithaK** [comment]
I haven't committed for a PR yet, but also I added `unescape_html()` to manifest_text to prevent HTML special characters from showing up in the manifest like a couple do in the zip here
```js
const manifest = JSON.parse(unescape_html(manifest_text));
```
[manifests.zip](https://github.com/devnoname120/google-play-book-downloader/files/12226031/manifests.zip)

**Comment by devnoname120** [comment]
Interesting.

So I see in the following in `manifest vSzFDwAAQBAJ.json` and `manifest xpKkDwAAQBAJ.json`:
```
    "is_right_to_left": true,
```

Can you confirm that these two books have the odd and even pages reversed in the PDF that is produced by the tool? And can you confirm that the remaining book `EzGDwAAQBAJ` doesn't have issues?

**Comment by KodywithaK** [comment]
Yes, that's true; on vSzF and xpKk I had to move the page order around to look as it should

**Comment by devnoname120** [comment]
@KodywithaK Any chance you could share one of the reverse-order books with me? Downloaded/converted to PDF without your changes.

You can find my email address in my profile. You can upload the ZIP here: https://cloud.paul.garden/s/8yK5GxfTciyS2qW

**Comment by KodywithaK** [comment]
@devnoname120 I sent you an email with a google drive link, I think it was too large to be accepted on the cloud site
