### ISSUE TITLE
Higher zoom possible?

### ISSUE THREAD

**Issue by olivierberten** [devnoname120/google-play-book-downloader#9]
Hi!

Great script! I'm at last able to download my "big" books.

On my computer, google play books uses zoom 6, which has a better resolution than the downloaded ones. I changed it in the script but it still uses zoom 3. Is it possible to implement this?

Yours,

**Comment by devnoname120** [comment]
Can you upload the raw images here for comparison purposes? Are you viewing the book on Google Play Books as `Flowing text` or `Original Pages`?

**Comment by olivierberten** [comment]
Hi!

I'm using Original Pages as this is a comic: https://play.google.com/books/reader?id=qSOWAwAAQBAJ

[Here's the image](https://github.com/devnoname120/google-play-book-downloader/assets/213117/986d893b-83da-45d0-a449-7efe63f0e570) downloaded by your script at max resolution:

[Here's the same one](https://github.com/devnoname120/google-play-book-downloader/assets/213117/fe893b48-39d3-4acc-89b6-6535392f90ef) downloaded with a limit at 1440x1920 to match the one in browser:

[The one in browser](https://github.com/devnoname120/google-play-book-downloader/assets/213117/733e97d6-0444-4050-b1d0-e2eac6045309) from url https://play.google.com/books/publisher/content/reader?id=qSOWAwAAQBAJ&hl=fr&pg=i_9782803632190_090&img=1&zoom=6&cds=2&sig=ACfU3U0gnPvLoQyyT6NK3xdKMRyjp_TCLQ&w=1440&h=1920&enc_all=1&source=ge-web-app 

And [decrypted by the browser](https://github.com/devnoname120/google-play-book-downloader/assets/213117/c49f634e-4845-4995-b59c-cd2c54675ce7)

Which is exactly the same as [in the downloaded epub](https://github.com/devnoname120/google-play-book-downloader/assets/213117/5b9a7a08-e68d-46f2-8c21-35878b3fd561)

**Comment by olivierberten** [comment]
Some interesting facts about https://play.google.com/books/publisher/content/reader?id=qSOWAwAAQBAJ&hl=fr&pg=i_9782803632190_090&img=1&zoom=6&cds=2&sig=ACfU3U0gnPvLoQyyT6NK3xdKMRyjp_TCLQ&w=1440&h=1920&enc_all=1&source=ge-web-app

- changing `enc_all` to 0 returns unencrypted and unmangled image
- `zoom=1` returns the same image, other values give an error
- removing the `w` and `h` parameters give the original size picture (in this case, it seems to actually be 1440x1920 as higher sizes do show artifacts)

That url is to be found in https://play.google.com/books/volumes/qSOWAwAAQBAJ/content/segment?start=h_9782803632190-tpc-90&cds=2&av=2&vert=1&ef=4&flvers=1&svg=2&multi_toc=1&hl=fr&source=gbs_content_api which is listed in https://play.google.com/books/reader?id=qSOWAwAAQBAJ

**Comment by devnoname120** [comment]
As far as I know this URL links to a specific image in the page. In your case the whole page happens to just consist of a single big image, which is the reason why you can easily download it with this URL.

You can try with this free book and see how it goes: https://play.google.com/store/books/details/Ryan_Shah_Master_the_Art_of_Unreal_Engine_4_Bluepr?id=cGbkAwAAQBAJ

**Comment by devnoname120** [comment]
This issue boils down to that: https://github.com/devnoname120/google-play-book-downloader/issues/15
